import Foundation
import PNG

let root = URL(fileURLWithPath: #filePath).deletingLastPathComponent().deletingLastPathComponent()
let input = root.appendingPathComponent("Resources/swift-bird.png")
let output = root.appendingPathComponent("Sources/SwiftBird.swift")

guard let image = try PNG.Image.decompress(path: input.path) else {
    fatalError("Cannot open \(input.path)")
}
let pixels = image.unpack(as: PNG.RGBA<UInt8>.self).map { pixel in
    ((pixel.a >> 6) << 6) | ((pixel.b >> 6) << 4)
        | ((pixel.g >> 6) << 2) | (pixel.r >> 6)
}

// Explicit stores avoid Swift heap allocation on the bare-metal SDK.
let stores = pixels.enumerated().map { index, pixel in
    String(format: "    destination[%d] = 0x%02X", index, Int(pixel))
}.joined(separator: "\n")
let source = """
    // Generated by Scripts/generate-swift-bird.swift from Resources/swift-bird.png.
    let birdWidth: UInt16 = \(image.size.x)
    let birdHeight: UInt16 = \(image.size.y)

    @c(swift_bird_copy)
    public func copyBird(_ destination: UnsafeMutablePointer<UInt8>, _ capacity: UInt32) -> UInt32 {
        guard capacity >= \(pixels.count) else { return 0 }
        var pixels = MutableSpan(_unsafeStart: destination, count: \(pixels.count))
        return copyBird(into: &pixels)
    }

    func copyBird(into destination: inout MutableSpan<UInt8>) -> UInt32 {
        guard destination.count >= \(pixels.count) else { return 0 }
    \(stores)
        return \(pixels.count)
    }

    """
try source.write(to: output, atomically: true, encoding: .utf8)
print("Generated \(output.path)")
